// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSaXfDJFD8kN8MWKlPcSHvwUostLu6Phk',
    appId: '1:214791865355:android:32b57c8f69faa8dbfc330e',
    messagingSenderId: '214791865355',
    projectId: 'muslim-693c4',
    storageBucket: 'muslim-693c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UW9QDkLhDF6N6q8wRwwKwDimxn5SvZE',
    appId: '1:214791865355:ios:94a546d02b275cddfc330e',
    messagingSenderId: '214791865355',
    projectId: 'muslim-693c4',
    storageBucket: 'muslim-693c4.firebasestorage.app',
    iosBundleId: 'com.example.tasbeeh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_UW9QDkLhDF6N6q8wRwwKwDimxn5SvZE',
    appId: '1:214791865355:ios:94a546d02b275cddfc330e',
    messagingSenderId: '214791865355',
    projectId: 'muslim-693c4',
    storageBucket: 'muslim-693c4.firebasestorage.app',
    iosBundleId: 'com.example.tasbeeh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaO4UDyLjKZ6Z2ohL8vA1CXFFcS0Ivr5s',
    appId: '1:214791865355:web:fe71826a85fb6555fc330e',
    messagingSenderId: '214791865355',
    projectId: 'muslim-693c4',
    authDomain: 'muslim-693c4.firebaseapp.com',
    storageBucket: 'muslim-693c4.firebasestorage.app',
    measurementId: 'G-L9MPMJBHNQ',
  );
}
